(executable
 (name test_consumer_integration)
 (modules test_consumer_integration)
 (libraries kafka_eio_consumer kafka_eio_producer kafka_eio_core kafka_test_helpers alcotest eio_main unix))

(rule
 (alias runtest-integration)
 (action (run ./test_consumer_integration.exe)))

(test
 (name test_consumer_unit)
 (modules test_consumer_unit)
 (libraries kafka_eio_consumer kafka_eio_core alcotest eio_main unix))
