(library
 (name kafka_eio_core)
 (public_name kafka-eio.core)
 (wrapped false)
 (modules kafka_raw kafka_error kafka_consumer_handle kafka_security)
 (foreign_stubs
  (language c)
  (names kafka_stubs)
  (flags (:standard -I/usr/local/include -I/opt/homebrew/include)))
 (c_library_flags (-L/usr/local/lib -L/opt/homebrew/lib -lrdkafka)))
