(library
 (name kafka_test_brokers)
 (modules kafka_test_brokers))

(library
 (name kafka_test_helpers)
 (modules kafka_test_helpers)
 (libraries kafka_eio kafka_test_brokers))

(test
 (name test_kafka_error)
 (modules test_kafka_error)
 (libraries kafka_eio alcotest))

(test
 (name test_kafka_security)
 (modules test_kafka_security)
 (libraries kafka_eio alcotest unix))
